version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: curasnap-redis
    ports:
      - "127.0.0.1:6379:6379"  # SECURITY: Bind only to localhost
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-defaultpass} --maxmemory 256mb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpass}
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-defaultpass}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: curasnap-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpass}
      # Health Check Configuration
      - HEALTH_DATABASE_TIMEOUT=3000
      - HEALTH_TRANSCRIPTION_TIMEOUT=5000
      - HEALTH_TRANSCRIPTION_URL=http://transcription-service:8002/health
      - HEALTH_AGENT_TIMEOUT=5000
      - HEALTH_AGENT_URL=http://agent-service:8001/health
      # Service URLs for internal communication
      - AGENT_SERVICE_URL=http://agent-service:8001
      - TRANSCRIPTION_SERVICE_URL=http://transcription-service:8002
    depends_on:
      redis:
        condition: service_healthy
      agent-service:
        condition: service_healthy
      transcription-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  agent-service:
    build:
      context: ./agent_service
      dockerfile: Dockerfile
    container_name: curasnap-agent
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  transcription-service:
    build:
      context: ./transcription_service
      dockerfile: Dockerfile
    container_name: curasnap-transcription
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 90s  # Whisper model loading takes time
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G  # Whisper models need more memory
          cpus: '2.0'

volumes:
  redis_data: